const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Turret,
		C3.Behaviors.Follow,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.ResetDoubleJump,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetTimescale
	];
};
self.C3_JsPropNameTable = [
	{p1: 0},
	{透明選擇框: 0},
	{黑幕: 0},
	{Sprite5: 0},
	{stopGame: 0},
	{黑幕2: 0},
	{故事視窗: 0},
	{故事視窗2: 0},
	{故事視窗3: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{跳躍穿透: 0},
	{boss戰場景穿透平台: 0},
	{實體: 0},
	{新手教學boss戰場景Tilemap: 0},
	{新手教學遊戲場景Tilemap: 0},
	{遊戲場景Tilemap: 0},
	{平鋪背景: 0},
	{桃樂絲右影子: 0},
	{桃樂絲右影子_s: 0},
	{桃樂絲右影子_s2: 0},
	{桃樂絲左影子: 0},
	{桃樂絲左影子_s: 0},
	{桃樂絲左影子_s2: 0},
	{平台: 0},
	{視野跟隨: 0},
	{邊界約束: 0},
	{桃樂絲: 0},
	{桃樂絲HP: 0},
	{桃樂絲HP_UI: 0},
	{桃樂絲傷害碰撞: 0},
	{子彈: 0},
	{出界銷毀: 0},
	{桃樂絲劍波: 0},
	{桃樂絲造成傷害碰撞: 0},
	{角色戰鬥畫面UI: 0},
	{角色戰鬥畫面UI＿重攻擊: 0},
	{角色戰鬥畫面UI＿普攻: 0},
	{角色戰鬥畫面UI＿遠程攻擊: 0},
	{角色戰鬥畫面UI＿衝刺: 0},
	{桃樂絲大招能量_UI: 0},
	{桃樂絲大招能量值: 0},
	{桃樂絲大招能量_UI2: 0},
	{桃樂絲大招能量_UI3: 0},
	{角色畫面UI_金錢: 0},
	{角色畫面金錢: 0},
	{提示1: 0},
	{互動提示: 0},
	{提示2: 0},
	{提示3: 0},
	{提示4: 0},
	{提示5: 0},
	{提示6: 0},
	{提示7: 0},
	{提示8: 0},
	{新手教學傳送門1: 0},
	{新手教學傳送門2: 0},
	{boss傳送門: 0},
	{提示11: 0},
	{提示_挑戰1_ez: 0},
	{提示_挑戰1_nor: 0},
	{提示_挑戰1_hard: 0},
	{提示_挑戰2_ez: 0},
	{提示_挑戰2_hard: 0},
	{提示_挑戰2_nor: 0},
	{挑戰門: 0},
	{炮台: 0},
	{紅色史萊姆01: 0},
	{紅色史萊姆01_hp: 0},
	{紅色史萊姆01_子彈: 0},
	{紅色史萊姆01_子彈2: 0},
	{紅色史萊姆01_子彈3: 0},
	{紅色史萊姆01_重生點: 0},
	{Follow: 0},
	{藍色史萊姆01: 0},
	{藍色史萊姆01_hp: 0},
	{藍色史萊姆01_重生點: 0},
	{藍色史萊姆02: 0},
	{藍色史萊姆02_hp: 0},
	{藍色史萊姆02_重生點: 0},
	{騎士長: 0},
	{騎士長_技能2: 0},
	{騎士長_生成點: 0},
	{騎士長傷害判定: 0},
	{騎士長雕像: 0},
	{boss_hpui: 0},
	{騎士長頭貼: 0},
	{boss_hp_text: 0},
	{對話框: 0},
	{桃樂絲立繪: 0},
	{騎士長立繪: 0},
	{劇情觸發: 0},
	{Text: 0},
	{劇情觸發2: 0},
	{製作者: 0},
	{金錢: 0},
	{物品選擇1: 0},
	{物品選擇2: 0},
	{物品選擇3: 0},
	{武器: 0},
	{防具: 0},
	{戒指: 0},
	{項鍊: 0},
	{武器名稱: 0},
	{戒指名稱: 0},
	{防具名稱: 0},
	{項鍊名稱: 0},
	{武器說明: 0},
	{戒指說明: 0},
	{防具說明: 0},
	{項鍊說明: 0},
	{補品: 0},
	{補品數量: 0},
	{HP_LVPoint: 0},
	{ATK_LVPoint: 0},
	{DEF_LVPoint: 0},
	{AGI_LVPoint: 0},
	{LV: 0},
	{EX: 0},
	{PT: 0},
	{HP: 0},
	{ATK: 0},
	{DEF: 0},
	{AGI: 0},
	{player_esc: 0},
	{item_box_武器: 0},
	{item_box_戒指: 0},
	{item_box_防具: 0},
	{item_box_項鍊: 0},
	{物品選擇框1: 0},
	{物品選擇框2: 0},
	{物品選擇框3: 0},
	{物品選擇框1_名稱: 0},
	{物品選擇框2_名稱: 0},
	{物品選擇框3_名稱: 0},
	{物品選擇框1_說明: 0},
	{物品選擇框2_說明: 0},
	{物品選擇框3_說明: 0},
	{補品藥水: 0},
	{武器_劍1: 0},
	{武器_劍2: 0},
	{武器_劍3: 0},
	{戒指_1: 0},
	{戒指_2: 0},
	{戒指_3: 0},
	{防具_1: 0},
	{防具_2: 0},
	{防具_3: 0},
	{項鍊_1: 0},
	{項鍊_2: 0},
	{項鍊_3: 0},
	{金錢圖示: 0},
	{說明: 0},
	{商店介面: 0},
	{商店物品框_補品: 0},
	{商店物品框_武器: 0},
	{商店物品框_武器2: 0},
	{商店物品框_武器3: 0},
	{商店物品框_戒指: 0},
	{商店物品框_戒指2: 0},
	{商店物品框_戒指3: 0},
	{商店物品框_防具: 0},
	{商店物品框_防具2: 0},
	{商店物品框_防具3: 0},
	{商店物品框_項鍊: 0},
	{商店物品框_項鍊2: 0},
	{商店物品框_項鍊3: 0},
	{鍵盤: 0},
	{測試用假人: 0},
	{測試用假人HP: 0},
	{測試場景Tilemap: 0},
	{新手教學_trainingDummy: 0},
	{新手教學_trainingDummy2: 0},
	{新手教學_shop: 0},
	{音頻: 0},
	{滑鼠: 0},
	{player_basic_damage_taken: 0},
	{player_basic_damage_taken_cd: 0},
	{player_basic_damage_taken_system: 0},
	{player_look: 0},
	{player_action: 0},
	{skill_on: 0},
	{player_act_cd_x: 0},
	{player_act_heavy_atk: 0},
	{player_act_heavy_atk1_dmg_s: 0},
	{player_act_heavy_atk2_dmg_m: 0},
	{player_act_falling_distance: 0},
	{player_act_cd_c: 0},
	{player_sword: 0},
	{player_sword2: 0},
	{player_sword3: 0},
	{player_skills_c_dmg: 0},
	{player_sword_dmg: 0},
	{player_act_cd_s: 0},
	{player_act_cd_s2: 0},
	{player_act_s_on: 0},
	{player_act_s_on_dmgup: 0},
	{player_act_cd_ctrl: 0},
	{player_act_speed: 0},
	{player_value_hp: 0},
	{player_value_hp_upper_limit: 0},
	{player_value_def: 0},
	{player_value_agi: 0},
	{player_value_atk: 0},
	{player_exp: 0},
	{player_exp_up: 0},
	{player_lvl: 0},
	{player_money: 0},
	{player_lvl_points: 0},
	{player_lvl_points_hp: 0},
	{player_lvl_points_def: 0},
	{player_lvl_points_agi: 0},
	{player_lvl_points_atk: 0},
	{player_item_hp: 0},
	{player_item_def: 0},
	{player_item_agi: 0},
	{player_item_atk: 0},
	{player_item_arms1: 0},
	{player_item_arms2: 0},
	{player_item_arms3: 0},
	{player_item_armor1: 0},
	{player_item_armor2: 0},
	{player_item_armor3: 0},
	{player_item_ring1: 0},
	{player_item_ring2: 0},
	{player_item_ring3: 0},
	{player_item_necklace1: 0},
	{player_item_necklace2: 0},
	{player_item_necklace3: 0},
	{player_equipment_arms: 0},
	{player_equipment_armor: 0},
	{player_equipment_ring: 0},
	{player_equipment_necklace: 0},
	{player_equipment_system: 0},
	{player_item_heal: 0},
	{player_equipment_heal_cd: 0},
	{system_shop_touch: 0},
	{system_shop: 0},
	{system_buy_wait: 0},
	{system_interface: 0},
	{system_interface2: 0},
	{test_dummy_hp: 0},
	{mon_blue_slime_1_hp: 0},
	{mon_blue_slime_1_spawn: 0},
	{mon_blue_slime_2_hp: 0},
	{mon_blue_slime_2_spawn: 0},
	{mon_red_slime_1_hp: 0},
	{mon_red_slime_1_spawn: 0},
	{"0_100_random": 0},
	{system_mon_atk: 0},
	{mon_boss1_hp: 0},
	{mon_boss1_action: 0},
	{mon_boss1_look: 0},
	{mon_boss1_move: 0},
	{mon_boss1_skill1: 0},
	{mon_boss1_skill2: 0},
	{mon_boss1_skill2_cd: 0},
	{mon_boss1_skill3: 0},
	{mon_boss1_skill3_cd: 0},
	{mon_boss1: 0},
	{system_store: 0},
	{system_store2: 0},
	{system_store_wait: 0},
	{system_store_pages: 0},
	{system_store_start: 0},
	{system_hint: 0},
	{system_text_speed: 0},
	{system_hint_no: 0},
	{system_mod_difficulty: 0},
	{system_challenge: 0},
	{system01: 0},
	{system_load: 0},
	{game_load: 0},
	{system_wait: 0},
	{system_mod: 0},
	{system_black_bg: 0},
	{system_black_bg2: 0}
];

self.InstanceType = {
	p1: class extends self.ISpriteInstance {},
	透明選擇框: class extends self.ISpriteInstance {},
	黑幕: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	stopGame: class extends self.ISpriteInstance {},
	黑幕2: class extends self.ISpriteInstance {},
	故事視窗: class extends self.ISpriteInstance {},
	故事視窗2: class extends self.ISpriteInstance {},
	故事視窗3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	boss戰場景穿透平台: class extends self.ITilemapInstance {},
	新手教學boss戰場景Tilemap: class extends self.ITilemapInstance {},
	新手教學遊戲場景Tilemap: class extends self.ITilemapInstance {},
	遊戲場景Tilemap: class extends self.ITilemapInstance {},
	平鋪背景: class extends self.ITiledBackgroundInstance {},
	桃樂絲右影子: class extends self.ISpriteInstance {},
	桃樂絲右影子_s: class extends self.ISpriteInstance {},
	桃樂絲右影子_s2: class extends self.ISpriteInstance {},
	桃樂絲左影子: class extends self.ISpriteInstance {},
	桃樂絲左影子_s: class extends self.ISpriteInstance {},
	桃樂絲左影子_s2: class extends self.ISpriteInstance {},
	桃樂絲: class extends self.ISpriteInstance {},
	桃樂絲HP: class extends self.ITextInstance {},
	桃樂絲HP_UI: class extends self.ISpriteInstance {},
	桃樂絲傷害碰撞: class extends self.ISpriteInstance {},
	桃樂絲劍波: class extends self.ISpriteInstance {},
	桃樂絲造成傷害碰撞: class extends self.ISpriteInstance {},
	角色戰鬥畫面UI: class extends self.ISpriteInstance {},
	角色戰鬥畫面UI＿重攻擊: class extends self.ISpriteInstance {},
	角色戰鬥畫面UI＿普攻: class extends self.ISpriteInstance {},
	角色戰鬥畫面UI＿遠程攻擊: class extends self.ISpriteInstance {},
	角色戰鬥畫面UI＿衝刺: class extends self.ISpriteInstance {},
	桃樂絲大招能量_UI: class extends self.ISpriteInstance {},
	桃樂絲大招能量值: class extends self.ITextInstance {},
	桃樂絲大招能量_UI2: class extends self.ISpriteInstance {},
	桃樂絲大招能量_UI3: class extends self.ISpriteInstance {},
	角色畫面UI_金錢: class extends self.ISpriteInstance {},
	角色畫面金錢: class extends self.ITextInstance {},
	提示1: class extends self.ISpriteInstance {},
	互動提示: class extends self.ISpriteInstance {},
	提示2: class extends self.ISpriteInstance {},
	提示3: class extends self.ISpriteInstance {},
	提示4: class extends self.ISpriteInstance {},
	提示5: class extends self.ISpriteInstance {},
	提示6: class extends self.ISpriteInstance {},
	提示7: class extends self.ISpriteInstance {},
	提示8: class extends self.ISpriteInstance {},
	新手教學傳送門1: class extends self.ISpriteInstance {},
	新手教學傳送門2: class extends self.ISpriteInstance {},
	boss傳送門: class extends self.ISpriteInstance {},
	提示11: class extends self.ISpriteInstance {},
	提示_挑戰1_ez: class extends self.ISpriteInstance {},
	提示_挑戰1_nor: class extends self.ISpriteInstance {},
	提示_挑戰1_hard: class extends self.ISpriteInstance {},
	提示_挑戰2_ez: class extends self.ISpriteInstance {},
	提示_挑戰2_hard: class extends self.ISpriteInstance {},
	提示_挑戰2_nor: class extends self.ISpriteInstance {},
	挑戰門: class extends self.ISpriteInstance {},
	紅色史萊姆01: class extends self.ISpriteInstance {},
	紅色史萊姆01_hp: class extends self.ISpriteInstance {},
	紅色史萊姆01_子彈: class extends self.ISpriteInstance {},
	紅色史萊姆01_子彈2: class extends self.ISpriteInstance {},
	紅色史萊姆01_子彈3: class extends self.ISpriteInstance {},
	紅色史萊姆01_重生點: class extends self.ISpriteInstance {},
	藍色史萊姆01: class extends self.ISpriteInstance {},
	藍色史萊姆01_hp: class extends self.ISpriteInstance {},
	藍色史萊姆01_重生點: class extends self.ISpriteInstance {},
	藍色史萊姆02: class extends self.ISpriteInstance {},
	藍色史萊姆02_hp: class extends self.ISpriteInstance {},
	藍色史萊姆02_重生點: class extends self.ISpriteInstance {},
	騎士長: class extends self.ISpriteInstance {},
	騎士長_技能2: class extends self.ISpriteInstance {},
	騎士長_生成點: class extends self.ISpriteInstance {},
	騎士長傷害判定: class extends self.ISpriteInstance {},
	騎士長雕像: class extends self.ISpriteInstance {},
	boss_hpui: class extends self.ISpriteInstance {},
	騎士長頭貼: class extends self.ISpriteInstance {},
	boss_hp_text: class extends self.ITextInstance {},
	對話框: class extends self.ISpriteInstance {},
	桃樂絲立繪: class extends self.ISpriteInstance {},
	騎士長立繪: class extends self.ISpriteInstance {},
	劇情觸發: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	劇情觸發2: class extends self.ISpriteInstance {},
	製作者: class extends self.ISpriteInstance {},
	金錢: class extends self.ISpriteInstance {},
	物品選擇1: class extends self.ISpriteInstance {},
	物品選擇2: class extends self.ISpriteInstance {},
	物品選擇3: class extends self.ISpriteInstance {},
	武器: class extends self.ISpriteInstance {},
	防具: class extends self.ISpriteInstance {},
	戒指: class extends self.ISpriteInstance {},
	項鍊: class extends self.ISpriteInstance {},
	武器名稱: class extends self.ITextInstance {},
	戒指名稱: class extends self.ITextInstance {},
	防具名稱: class extends self.ITextInstance {},
	項鍊名稱: class extends self.ITextInstance {},
	武器說明: class extends self.ITextInstance {},
	戒指說明: class extends self.ITextInstance {},
	防具說明: class extends self.ITextInstance {},
	項鍊說明: class extends self.ITextInstance {},
	補品: class extends self.ISpriteInstance {},
	補品數量: class extends self.ITextInstance {},
	HP_LVPoint: class extends self.ISpriteInstance {},
	ATK_LVPoint: class extends self.ISpriteInstance {},
	DEF_LVPoint: class extends self.ISpriteInstance {},
	AGI_LVPoint: class extends self.ISpriteInstance {},
	LV: class extends self.ITextInstance {},
	EX: class extends self.ITextInstance {},
	PT: class extends self.ITextInstance {},
	HP: class extends self.ITextInstance {},
	ATK: class extends self.ITextInstance {},
	DEF: class extends self.ITextInstance {},
	AGI: class extends self.ITextInstance {},
	player_esc: class extends self.ISpriteInstance {},
	item_box_武器: class extends self.ISpriteInstance {},
	item_box_戒指: class extends self.ISpriteInstance {},
	item_box_防具: class extends self.ISpriteInstance {},
	item_box_項鍊: class extends self.ISpriteInstance {},
	物品選擇框1: class extends self.ISpriteInstance {},
	物品選擇框2: class extends self.ISpriteInstance {},
	物品選擇框3: class extends self.ISpriteInstance {},
	物品選擇框1_名稱: class extends self.ITextInstance {},
	物品選擇框2_名稱: class extends self.ITextInstance {},
	物品選擇框3_名稱: class extends self.ITextInstance {},
	物品選擇框1_說明: class extends self.ITextInstance {},
	物品選擇框2_說明: class extends self.ITextInstance {},
	物品選擇框3_說明: class extends self.ITextInstance {},
	補品藥水: class extends self.ISpriteInstance {},
	武器_劍1: class extends self.ISpriteInstance {},
	武器_劍2: class extends self.ISpriteInstance {},
	武器_劍3: class extends self.ISpriteInstance {},
	戒指_1: class extends self.ISpriteInstance {},
	戒指_2: class extends self.ISpriteInstance {},
	戒指_3: class extends self.ISpriteInstance {},
	防具_1: class extends self.ISpriteInstance {},
	防具_2: class extends self.ISpriteInstance {},
	防具_3: class extends self.ISpriteInstance {},
	項鍊_1: class extends self.ISpriteInstance {},
	項鍊_2: class extends self.ISpriteInstance {},
	項鍊_3: class extends self.ISpriteInstance {},
	金錢圖示: class extends self.ISpriteInstance {},
	說明: class extends self.ITextInstance {},
	商店介面: class extends self.ISpriteInstance {},
	商店物品框_補品: class extends self.ISpriteInstance {},
	商店物品框_武器: class extends self.ISpriteInstance {},
	商店物品框_武器2: class extends self.ISpriteInstance {},
	商店物品框_武器3: class extends self.ISpriteInstance {},
	商店物品框_戒指: class extends self.ISpriteInstance {},
	商店物品框_戒指2: class extends self.ISpriteInstance {},
	商店物品框_戒指3: class extends self.ISpriteInstance {},
	商店物品框_防具: class extends self.ISpriteInstance {},
	商店物品框_防具2: class extends self.ISpriteInstance {},
	商店物品框_防具3: class extends self.ISpriteInstance {},
	商店物品框_項鍊: class extends self.ISpriteInstance {},
	商店物品框_項鍊2: class extends self.ISpriteInstance {},
	商店物品框_項鍊3: class extends self.ISpriteInstance {},
	鍵盤: class extends self.IInstance {},
	測試用假人: class extends self.ISpriteInstance {},
	測試用假人HP: class extends self.ITextInstance {},
	測試場景Tilemap: class extends self.ITilemapInstance {},
	新手教學_trainingDummy: class extends self.ISpriteInstance {},
	新手教學_trainingDummy2: class extends self.ISpriteInstance {},
	新手教學_shop: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	滑鼠: class extends self.IInstance {}
}